src/04.EndPoints/WebMvc/Controllers/ContactUsController.cs
using Queries.Informations;
using Services.Messages;
using Services.Messages.Contracts;
using Services.Messages.Contracts.Dto;
using WebMvc.Infrastructure.GoogleRecaptcha;

namespace WebMvc.Controllers;

public class ContactUsController : Controller
{
    private readonly IMessageService _messageService;
    private readonly IInformationQuery _informationQuery;
    private readonly IGoogleRecaptchaValidator _googleRecaptchaValidator;

    public ContactUsController(
        IMessageService messageService,
        IInformationQuery informationQuery,
        IGoogleRecaptchaValidator googleRecaptchaValidator)
    {
        _messageService = messageService;
        _informationQuery = informationQuery;
        _googleRecaptchaValidator = googleRecaptchaValidator;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        ViewData["Information"] = await _informationQuery.Get();
        return View();
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(AddMessageByContactViewModel message)
    {
        ViewData["Information"] = await _informationQuery.Get();

        if (!await _googleRecaptchaValidator.IsCaptchaPassed(message.Captcha!))
        {
            ViewData["FormSubmitResult"] = false;
            return View(message);
        }

        if (!ModelState.IsValid)
        {
            return View(message);
        }

        await _messageService.Add(new AddMessageByContactDto()
        {
            Text = message.Text,
            Email = message.Email,
            Name = message.Name
        });


        ViewData["FormSubmitResult"] = true;

        return View();
    }
}

src/04.EndPoints/WebMvc/Controllers/ResumeController.cs
namespace WebMvc.Controllers;

public class ResumeController : Controller
{
    private readonly IEducationQuery _educationQuery;
    private readonly IExperienceQuery _experienceQuery;
    private readonly ISkillQuery _skillQuery;

    public ResumeController(
        IEducationQuery educationQuery,
        IExperienceQuery experienceQuery,
        ISkillQuery skillQuery)
    {
        _educationQuery = educationQuery;
        _experienceQuery = experienceQuery;
        _skillQuery = skillQuery;
    }
    
    public async Task<IActionResult> Index()
    {
        var educations = await _educationQuery.GetAll();
        var experience = await _experienceQuery.GetAll();
        var skills = await _skillQuery.GetAll();

        var model = new ResumeViewModel()
        {
            Educations = educations
                .Select(_=> new GetEducationsViewModel()
                {
                    Id = _.Id,
                    Description = _.Description,
                    Order = _.Order,
                    Title = _.Title,
                    EndDate = _.EndDate,
                    StartDate = _.StartDate
                }).ToList(),
             Experiences = experience
                 .Select(_=> new GetExperiencesViewModel()
                 {
                     Id = _.Id,
                     Description = _.Description,
                     Order = _.Order,
                     Title = _.Title,
                     EndDate = _.EndDate,
                     StartDate = _.StartDate
                 }).ToList(), 
             Skills = skills
                 .Select(_=> new GetSkillsViewModel()
                 {
                     Id = _.Id,
                     Order = _.Order,
                     Title = _.Title,
                     Percent = _.Percent
                 }).ToList(),
        };
        return View(model);
    }
}

src/04.EndPoints/WebMvc/Controllers/WorkSamplesController.cs
using Queries.WorkSampleCategories;
using Queries.WorkSamples;

namespace WebMvc.Controllers;

public class WorkSamplesController  : Controller
{
    private readonly IWorkSampleQuery _workSampleQuery;
    private readonly IWorkSampleCategoryQuery _workSampleCategoryQuery;

    public WorkSamplesController(
        IWorkSampleQuery workSampleQuery,
        IWorkSampleCategoryQuery workSampleCategoryQuery)
    {
        _workSampleQuery = workSampleQuery;
        _workSampleCategoryQuery = workSampleCategoryQuery;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var workSamples = await _workSampleQuery.GetAll();
        var categories = await _workSampleCategoryQuery.GetAll();
        var index = new WorkSampleIndexViewModel()
        {
            WorkSamples = workSamples.Select(_ => new GetAllWorkSampleViewModel()
            {
                Id = _.Id,
                Order = _.Order,
                Title = _.Title,
                ImageAlt = _.ImageAlt,
                Link = _.Link,
                Image = _.Image,
                CategoryId = _.CategoryId
            }).ToList(),
            WorkSampleCategories = categories.Select(_ => new GetAllWorkSampleCategoryViewModel()
            {
                Id = _.Id,
                Order = _.Order,
                Title = _.Title
            }).ToList()
        };
        return View(index);
    }
}

src/04.EndPoints/WebMvc/ViewComponents/SideBarViewComponent.cs
using Queries.Informations;
using WebMvc.ViewModels.Informations;

namespace WebMvc.ViewComponents;

public class SideBarViewComponent : ViewComponent
{
    private readonly ISocialMediaQuery _socialMediaQuery;
    private readonly IInformationQuery _informationQuery;

    public SideBarViewComponent(
        ISocialMediaQuery socialMediaQuery,
        IInformationQuery informationQuery)
    {
        _socialMediaQuery = socialMediaQuery;
        _informationQuery = informationQuery;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var socialMedia = await _socialMediaQuery.GetAll();
        var information = await _informationQuery.Get();

        var model = new SideBarViewModel()
        {
            SocialMedias = socialMedia.Select(_ => new GetAllSocialMediaViewModel()
                {
                    Icon = _.Icon,
                    Id = _.Id,
                    Link = _.Link,
                    Order = _.Order
                })
                .ToList(),
            Information = information is null 
            ? new GetInformationViewModel()
            : new GetInformationViewModel()
            {
                Id = information.Id,
                Address = information.Address,
                Avatar =  information.Avatar,
                Email = information.Email,
                Job = information.Job,
                Name = information.Name,
                Phone = information.Phone,
                MapSrc = information.MapSrc,
                ResumeFile = information.ResumeFile,
                DateOfBirth = information.DateOfBirth
            }
        };

        return View("SideBar", model);
    }
}

src/04.EndPoints/WebMvc/Views/Shared/_CaptchaScriptPartial.cshtml
@inject IOptions<GoogleRecaptchaConfig> GoogleRecaptchaConfig;
@{
    var siteKey = GoogleRecaptchaConfig.Value.SiteKey;
}

<script src="https://www.google.com/recaptcha/api.js?render=@siteKey"></script>
<script>
    grecaptcha.ready(function() {
        window.grecaptcha.execute('@siteKey', { action: 'home' }).then(function (token) {
            $("#Captcha").val(token);
        });
    });
</script>

src/04.EndPoints/WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
    <partial name="_MetaTag" />
    <partial name="_Style" />
</head>

<body class="bg-triangles-2">

<partial name="_Preloader" />

<main class="main">

    <partial name="_Menu" />

    <div class="wrapper">

        @await Component.InvokeAsync("SideBar")

        <div class="content js-scroll">
            @RenderBody()
        </div>

    </div>

</main>

<partial name="_Svg" />
<partial name="_Scripts" />

@await RenderSectionAsync("Scripts", false)

</body>

</html>

src/04.EndPoints/WebMvc/Views/Shared/_Menu.cshtml
@{
    var controllerName = ViewContext.RouteData.Values["Controller"]!.ToString();
    var actionName = ViewContext.RouteData.Values["Action"]!.ToString();
}


<!-- Menu -->
<div class="circle-menu">
    <div class="hamburger">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="hamburger__text">منو</div>
    </div>
</div>

<div class="nav-wrap">
    <ul class="nav">
        <li class="nav__item">
            <a asp-controller="Home" asp-action="Index" class="@(controllerName == "Home" && actionName == "Index" ? "active" : "")">درباره من</a>
        </li>
        <li class="nav__item">
            <a asp-controller="Resume" asp-action="Index" class="@(controllerName == "Resume" && actionName == "Index" ? "active" : "")">رزومه</a>
        </li>
        <li class="nav__item">
            <a asp-controller="WorkSamples" asp-action="Index" class="@(controllerName == "WorkSamples" && actionName == "Index" ? "active" : "")">نمونه کارها</a>
        </li>
        <li class="nav__item">
            <a asp-controller="ContactUs" asp-action="Index" class="@(controllerName == "ContactUs" && actionName == "Index" ? "active" : "")">تماس با من</a>
        </li>
    </ul>
</div>

src/04.EndPoints/WebMvc/Views/Shared/_MetaTag.cshtml
<meta charset="UTF-8">
<meta name="googlebot" content="index,follow">
<meta name="robots" content="noodp,noydir">
<meta http-equiv="X-UA-Compatible" content="IE-edge,chrome=1">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1">

src/04.EndPoints/WebMvc/Views/Shared/_Preloader.cshtml
<div class="preloader">
    <div class="preloader__wrap">
        <svg class="spinner-container" viewBox="0 0 52 52">
            <circle class="path" cx="26px" cy="26px" r="20px" fill="none" stroke-width="4px"></circle>
        </svg>
        <div class="preloader__progress"><span></span></div>
    </div>
</div>

src/04.EndPoints/WebMvc/Views/Shared/_Scripts.cshtml
<script src="/site/js/jquery-3.4.1.min.js"></script>
<script src="/site/js/plugins.min.js"></script>
<script src="/site/js/common.js"></script>
<script src="/site/demo/plugins-demo.js"></script>
<script src="/custom/css/customStyle.css"></script>

src/04.EndPoints/WebMvc/Views/Shared/_Style.cshtml
<title>قالب رزومه</title>
<!-- Favicons -->
<link rel="apple-touch-icon" sizes="144x144" href="/site/images/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="114x114" href="/site/images/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="72x72" href="/site/images/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="57x57" href="/site/images/favicons/apple-touch-icon-57x57.png">
<link rel="shortcut icon" href="/site/images/favicons/favicon.png" type="image/png">

<!-- Styles -->
<link rel="stylesheet" type="text/css" href="/site/styles/style.css" />
<link rel="stylesheet" type="text/css" href="/site/styles/style-rtl.css" />
<link rel="stylesheet" type="text/css" href="/site/demo/style-demo.css" />
<link href="/lib/fontawesome/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="/custom/css/customStyle.css" rel="stylesheet">

src/04.EndPoints/WebMvc/Views/Shared/_Svg.cshtml
<svg class="svg-defs">
    <clipPath id="avatar-box">
        <path d="M1.85379 38.4859C2.9221 18.6653 18.6653 2.92275 38.4858 1.85453 56.0986.905299 77.2792 0 94 0c16.721 0 37.901.905299 55.514 1.85453 19.821 1.06822 35.564 16.81077 36.632 36.63137C187.095 56.0922 188 77.267 188 94c0 16.733-.905 37.908-1.854 55.514-1.068 19.821-16.811 35.563-36.632 36.631C131.901 187.095 110.721 188 94 188c-16.7208 0-37.9014-.905-55.5142-1.855-19.8205-1.068-35.5637-16.81-36.63201-36.631C.904831 131.908 0 110.733 0 94c0-16.733.904831-37.9078 1.85379-55.5141z"></path>
    </clipPath>
    <clipPath id="avatar-hexagon">
        <path d="M0 27.2891c0-4.6662 2.4889-8.976 6.52491-11.2986L31.308 1.72845c3.98-2.290382 8.8697-2.305446 12.8637-.03963l25.234 14.31558C73.4807 18.3162 76 22.6478 76 27.3426V56.684c0 4.6805-2.5041 9.0013-6.5597 11.3186L44.4317 82.2915c-3.9869 2.278-8.8765 2.278-12.8634 0L6.55974 68.0026C2.50414 65.6853 0 61.3645 0 56.684V27.2891z"></path>
    </clipPath>
</svg>