src/04.EndPoints/WebMvc/ViewModels/Works/AddWorkViewModel.cs
namespace WebMvc.ViewModels.Works;

public class AddWorkViewModel
{
    public  string Id { get; set; }
    
    [Display(Name = "آیکون")]
    public  string Icon { get; set; }
    
    [Display(Name = "عنوان")]
    public  string Title { get; set; }

    [Display(Name = "توضیحات")]
    public  string Description { get; set; }

    [Display(Name = "عرض ستون آیتم")]
    public  int ColumnLg { get; set; }

    [Display(Name = "الویت")]
    public  int Order { get; set; }
}

src/04.EndPoints/WebMvc/ViewModels/Works/GetWorkByIdViewModel.cs
namespace WebMvc.ViewModels.Works;

public class GetWorkByIdViewModel
{
    public required string Id { get; set; }
    
    [Display(Name = "آیکون")]
    public required string Icon { get; set; }
    
    [Display(Name = "عنوان")]
    public required string Title { get; set; }

    [Display(Name = "توضیحات")]
    public required string Description { get; set; }

    [Display(Name = "عرض ستون آیتم")]
    public required int ColumnLg { get; set; }

    [Display(Name = "الویت")]
    public required int Order { get; set; }
}

src/04.EndPoints/WebMvc/ViewModels/Works/GetWorksViewModel.cs
namespace WebMvc.ViewModels.Works;

public class GetWorksViewModel
{
    public required string Id { get; set; }
    
    [Display(Name = "آیکون")]
    public required string Icon { get; set; }
    
    [Display(Name = "عنوان")]
    public required string Title { get; set; }

    [Display(Name = "توضیحات")]
    public required string Description { get; set; }

    [Display(Name = "عرض ستون آیتم")]
    public required int ColumnLg { get; set; }

    [Display(Name = "الویت")]
    public required int Order { get; set; }
}

src/04.EndPoints/WebMvc/ViewModels/Works/UpdateWorkViewModel.cs
namespace WebMvc.ViewModels.Works;

public class UpdateWorkViewModel
{
    public  string Id { get; set; }
    
    [Display(Name = "آیکون")]
    public  string Icon { get; set; }
    
    [Display(Name = "عنوان")]
    public  string Title { get; set; }

    [Display(Name = "توضیحات")]
    public  string Description { get; set; }

    [Display(Name = "عرض ستون آیتم")]
    public  int ColumnLg { get; set; }

    [Display(Name = "الویت")]
    public  int Order { get; set; }
}

src/04.EndPoints/WebMvc/Areas/Admin/Controllers/WorkController.cs
using Services.Exceptions;

namespace WebMvc.Areas.Admin.Controllers;

public class WorkController : AdminBaseController
{
    private readonly IWorkQuery _workQuery;
    private readonly IMapper _mapper;
    private readonly IWorkService _workService;

    public WorkController(
        IWorkQuery workQuery,
        IMapper mapper,
        IWorkService workService)
    {
        _workQuery = workQuery;
        _mapper = mapper;
        _workService = workService;
    }

    public async Task<IActionResult> Index()
    {
        var works = await _workQuery.GetAll();

        var model = _mapper.Map<List<GetWorksViewModel>>(works);

        return View(model);
    }

    #region Create

    public IActionResult LoadCreateModal(string id)
    {
        return PartialView("CreateModalPartial", new AddWorkViewModel());
    }

    public async Task<IActionResult> Create(AddWorkViewModel model)
    {
        try
        {
            var work = _mapper.Map<AddWorkDto>(model);
            await _workService.Add(work);

            return new JsonResult(new { status = "Success" });
        }
        catch (IdIsDuplicateException)
        {
            return new JsonResult(new
            {
                status = "Error",
                errorMessage = "ایدی تکراری است"
            });
        }
        catch
        {
            return new JsonResult(new
            {
                status = "Error",
                errorMessage = "خطایی رخ داده است"
            });
        }
    }

    #endregion

    #region Update

    public async Task<IActionResult> LoadUpdateModal(string id)
    {
        var work = await _workQuery.Find(_ => _.Id == id);
        var model = _mapper.Map<UpdateWorkViewModel>(work);
        return PartialView("_updateModalPartial", model);
    }

    public async Task<IActionResult> Update(UpdateWorkViewModel model)
    {
        try
        {
            var dto = _mapper.Map<UpdateWorkDto>(model);
            await _workService.Update(dto);

            return new JsonResult(new { status = "Success" });
        }
        catch (IdIsDuplicateException)
        {
            return new JsonResult(new
            {
                status = "Error",
                errorMessage = "ایدی تکراری است"
            });
        }
        catch
        {
            return new JsonResult(new
            {
                status = "Error",
                errorMessage = "خطایی رخ داده است"
            });
        }
    }

    #endregion


    public async Task<IActionResult> Delete(string id)
    {
        try
        {
            await _workService.Delete(id);
            return new JsonResult(new { status = "Success" });
        }
        catch
        {
            return new JsonResult(new
            {
                status = "Error",
                errorMessage = "خطایی رخ داده است"
            });
        }
    }
}

src/04.EndPoints/WebMvc/Areas/Admin/Views/Work/CreateModalPartial.cshtml
@model AddWorkViewModel


<form id="WorkCreate" asp-area="Admin" asp-controller="Work" asp-action="Create"
      data-ajax="true" data-ajax-begin="StartLoading()" data-ajax-success="WorkCreate">

    <div class="modal-header">
        <h5 class="modal-title">ایجاد</h5>
        <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>


    <div class="modal-body">

        <div class="row">
            <div class="col-12">


                <input type="hidden" asp-for="Id" value="@Guid.NewGuid().ToString()"/>

                <div class="form-group">
                    <label asp-for="Title"></label>
                    <div class="controls">
                        <input type="text" asp-for="Title" class="form-control">
                    </div>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Icon"></label>
                    <div class="controls">
                        <input type="text" asp-for="Icon" class="form-control">
                    </div>
                    <span asp-validation-for="Icon" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ColumnLg"></label>
                    <div class="controls">
                        <input type="number" asp-for="ColumnLg" class="form-control">
                    </div>
                    <span asp-validation-for="ColumnLg" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Order"></label>
                    <div class="controls">
                        <input type="number" asp-for="Order" class="form-control">
                    </div>
                    <span asp-validation-for="Order" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <div class="controls">
                        <textarea asp-for="Description" class="form-control"></textarea>
                    </div>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div>
                    <button type="submit" class="btn btn-bold btn-pure float-right btn-success">ثبت</button>
                </div>

            </div>
        </div>

    </div>

</form>

src/04.EndPoints/WebMvc/Areas/Admin/Views/Work/Index.cshtml
@model ICollection<GetWorksViewModel>


@{
    ViewData["Title"] = " کارهایی که انجام میدهم";
}

<div class="content-header">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="page-title">@ViewData["Title"]</h3>
        </div>
        <div class="right-title">
            <button type="button" onclick="LoadCreateModal()" class="btn btn-circle btn-success mb-5">
                <i class="mdi mdi-plus"></i>
            </button>
        </div>
    </div>
</div>

<section class="content">

    <div class="row">
        <div class="col-12">
            <div class="box">
                <div class="box-body" id="data-table-box">
                    <div class="table-responsive">
                        <table class="table table-hover no-wrap data-table">
                            <thead>
                            <tr class="bg-secondary">
                                <th>عنوان</th>
                                <th>توضیحات</th>
                                <th>سایز عرض</th>
                                <th>الویت</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>


                            @foreach (var item in Model)
                            {
                                <tr id="ListItem-@(item.Id)">
                                    <td>@item.Title</td>
                                    <td>@item.Description</td>
                                    <td>@item.ColumnLg</td>
                                    <td>@item.Order</td>
                                    <td>
                                        <button onclick="LoadUpdateModal('@item.Id')" class="btn btn-icon-circle btn-warning">
                                            <i class="ti-marker-alt"></i>
                                        </button>
                                        <button onclick="WorkDelete('@item.Id')" class="btn btn-icon-circle btn-danger">
                                            <i class="ti-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

src/04.EndPoints/WebMvc/Areas/Admin/Views/Work/_updateModalPartial.cshtml
@model UpdateWorkViewModel


<form id="WorkCreate" asp-area="Admin" asp-controller="Work" asp-action="Update"
      data-ajax="true" data-ajax-begin="StartLoading()" data-ajax-success="WorkUpdate">

    <div class="modal-header">
        <h5 class="modal-title">ایجاد</h5>
        <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>


    <div class="modal-body">

        <div class="row">
            <div class="col-12">


                <input type="hidden" asp-for="Id" value="@Model.Id"/>

                <div class="form-group">
                    <label asp-for="Title"></label>
                    <div class="controls">
                        <input type="text" asp-for="Title" class="form-control">
                    </div>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Icon"></label>
                    <div class="controls">
                        <input type="text" asp-for="Icon" class="form-control">
                    </div>
                    <span asp-validation-for="Icon" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ColumnLg"></label>
                    <div class="controls">
                        <input type="number" asp-for="ColumnLg" class="form-control">
                    </div>
                    <span asp-validation-for="ColumnLg" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Order"></label>
                    <div class="controls">
                        <input type="number" asp-for="Order" class="form-control">
                    </div>
                    <span asp-validation-for="Order" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <div class="controls">
                        <textarea asp-for="Description" class="form-control"></textarea>
                    </div>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div>
                    <button type="submit" class="btn btn-bold btn-pure float-right btn-success">ثبت</button>
                </div>

            </div>
        </div>

    </div>

</form>